version: "3.9"

services:
  hardhat-node:
    build: .
    ports:
      - "8545:8545"
    volumes:
      - ./artifacts:/app/artifacts # Persist compiled contracts
    environment:
      - NETWORK_ID=31337

  frontend:
    build: ./appfrontend
    ports:
      - "3000:80"
    depends_on:
      - hardhat-node
    environment:
      - REACT_APP_CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
