name: Frontend CI/CD

on:
  push:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Debug: List all files to verify structure
      - name: Debug Directory Structure
        run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: appfrontend/package-lock.json # Update path

      - name: Install Dependencies
        run: |
          cd appfrontend  # No "blockchain-scm" prefix
          npm install --prefer-offline

      - name: Run Tests
        run: npm test -- --watchAll=false --passWithNoTests
        working-directory: appfrontend # Simplified path

      - name: Build Frontend
        run: npm run build
        working-directory: appfrontend

  docker:
    name: Docker Image Build
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: |
          cd blockchain-scm/appfrontend
          docker build -t prayagtandon/frontend-app:latest .

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Frontend
        run: kubectl apply -f ./blockchain-scm/kubernetes/frontend-deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
